const userActionTypes = {
  FETCH_POSTS: "FETCH_POSTS",
  REQUEST_POSTS: "REQUEST_POSTS",
  ADD_NEW_POST: "ADD_NEW_POST",
  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  REQUEST_PROFILE: "REQUEST_PROFILE",
  FETCH_PROFILE: "FETCH_PROFILE",
  REQUEST_POST: "REQUEST_POST",
  FETCH_POST: "FETCH_POST",
  ADD_NEW_COMMENTS: "ADD_NEW_COMMENTS",
  REQUEST_PUT_POST: "REQUEST_PUT_POST",
  LOG_OUT: "LOG_OUT",
};

export default userActionTypes;
