const userActionTypes = {
  LOG_IN_START: "LOG_IN_START",
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
  LOG_IN_FAILURE: "LOG_IN_FAILURE",
  LOG_IN_WITH_LOCAL_STORAGE: "LOG_IN_WITH_LOCAL_STORAGE",
  REGISTER_START: "REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  LOG_OUT: "LOG_OUT",
  // FETCH_POSTS: "FETCH_POSTS",
  // REQUEST_POSTS: "REQUEST_POSTS",
  // ADD_NEW_POST: "ADD_NEW_POST",
  // ADD_POST_REQUEST: "ADD_POST_REQUEST",
  // REQUEST_PROFILE: "REQUEST_PROFILE",
  // FETCH_PROFILE: "FETCH_PROFILE",
  // REQUEST_POST: "REQUEST_POST",
  // FETCH_POST: "FETCH_POST",
  // ADD_NEW_COMMENTS: "ADD_NEW_COMMENTS",
  // REQUEST_PUT_POST: "REQUEST_PUT_POST",
};

export default userActionTypes;
